apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-v2
  labels:
    app: recommendation
    version: v2
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"  
    prometheus.io/scheme: "http" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: v2
  template:
    metadata:
      labels:
        app: recommendation
        version: v2
    spec:
      containers:
      - name: recommendation-container
        image: navkkrnair/istio-recommendation:2.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080   
            protocol: TCP
        securityContext:
          privileged: false